# Generated by Django 5.2.3 on 2025-06-25 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'рассылку', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
