# Generated by Django 5.2.3 on 2025-07-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_telegram_id_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_date',
        ),
    ]
